yolo_model:

  config_file:
    name: yolov3-tiny-cup_stop_arrow.cfg
  weight_file:
    name: tiny-yolo-cup_stop_arrow.weights
  threshold:
    value: 0.011
  detection_classes:
    names:
      - CUP
      - ROAD SIGN
      - STOP SIGN

      
